spring:
  application:
    name: Project3
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project_three_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  file:
    name: logging
    path: /
  level:
    root: info